### ISSUE TITLE
Capital of Israel is disputed

### ISSUE THREAD

**Issue by sesse** [anki-geo/ultimate-geography#389]
Hi,

Israel's capital is listed as Jerusalem, with no further note. Wikipedia describes it as disputed: “Recognition by other UN member states: Australia (West Jerusalem),[1] Russia (West Jerusalem),[2] the Czech Republic (West Jerusalem),[3] Honduras,[4] Guatemala,[5] Nauru,[6] and the United States.[7] In September 2020 it was reported that Serbia would be moving its embassy from Tel Aviv to Jerusalem.[8][9]” with link to: https://en.wikipedia.org/wiki/Status_of_Jerusalem

Suggested note (all of this is from the given Wikipedia article, with some parts removed that do not change the meaning, for brevity): “Disputed, with both Israel and Palestine claiming Jerusalem as capital. The majority of UN member states have favored locating their embassies in Tel Aviv.”

**Comment by ukanuk** [comment]
If strictly following the Contributing Guidelines, one could argue the note should stay as-is. English Wikipedia only lists Jerusalem in the infobox on the page for Israel, and the *Capital info* field is only described for use with countries with multiple capitals, not capitals with multiple countries. I don't see anyone claiming Tel Aviv is the capital; it appears some countries don't recognize any capital, and some countries recognize Jerusalem.

However, it doesn't seem unreasonable to include something in the info field. How about more simply:
"Disputed. Claimed by both Israel and Palestine."

If others feel extra info about Tel Aviv is necessary or especially useful, I feel the original suggestion could be misunderstood to suggest some countries claim Tel Aviv is the capital. I'd leave in one extra phrase from the Wikipedia article at the very end:
"Disputed. Claimed by both Israel and Palestine; the majority of UN member states have favored locating their embassies in Tel Aviv prior to a final status agreement."

**Comment by axelboc** [comment]
The current guidelines are not at odds with @sesse's _Capital info_ suggestion, but I feel it might be wise to remain as concise as possible and avoid mentioning embassies or Tel Aviv.

What is at odds with the current guidelines, however, is the fact that Jerusalem does not appear on the note of _Palestine_ at all even though the infobox says that it is the State of Palestine's proclaimed capital.

![image](https://user-images.githubusercontent.com/2936402/107130033-38c43f80-68ca-11eb-9f75-f77fdff2abbd.png)

> If the first capital is followed by a qualifier such as "official", "constitutional", "de jure", "claimed", or "political", it must be used alone in the Capital field. The Capital info field must then be used to detail the status and/or role of every capital - e.g. While Dodoma is the official capital, Dar es Salaam is the de facto seat of government.

If we are to stick to this guideline, Jerusalem should replace Ramallah as Palestine's capital, and both cities should be mentioned in the _Capital info_ field. Since two notes would share the same "main" capital, we'd have to add hints (which might be tricky to find, actually).

**Comment by sesse** [comment]
I hadn't come to the Ramallah card yet :-) I agree it's a tricky topic, and geopolitical issues always cause headaches. I'd be fine with not mentioning Tel Aviv, since there's no indication anyone has actually claimed it's the capital of Israel.

The best hint I could come up with at the spot would be something like “officially approved only by seven countries as of 2021” versus “does not control the area militarily”. I'm not sure if this is an acceptable way to go.

**Comment by admiral-ackbar** [comment]
I think @axelboc is right: the clear answer according to the guidelines is the make Jerusalem the capital of both of them, clarifying Ramallah as the administrative center of Palestine. As far as hints go, "Jewish Country", and "[Muslim/Islamic] Country" seem good enough.

**Comment by aplaice** [comment]
> I think @axelboc is right: the clear answer according to the guidelines is the make Jerusalem the capital of both of them, clarifying Ramallah as the administrative center of Palestine. As far as hints go, "Jewish Country", and "[Muslim/Islamic] Country" seem good enough.

Unfortunately, these are probably not the best, since the point of the capital hint (and of cues in general!) is to convey as little information as possible to not give away the answers.

For instance if you were to see this card:

```
Jerusalem

(Jewish country)
```

even if you were unaware that Jerusalem was actually the capital of Israel, you'd almost certainly be able to work out the answer. (How many other Jewish countries are there?)

**Comment by jamesnelmore** [comment]
That's true for Israel, but not necessarily for Palestine, because there are plenty of Muslim countries. So, what about "[Muslim/Islamic] Country" and "non-[Muslim/Islamic] Country"?

Side note: is "Muslim" or "Islamic" the correct term?

**Comment by axelboc** [comment]
I feel it's a bit reductive to hint at a country by its dominant religion. How about hinting at the status of the capital instead? Like "not the de facto capital", and "seat of government" or something of the sort.

**Comment by ohare93** [comment]
> I feel it's a bit reductive to hint at a country by its dominant religion. How about hinting at the status of the capital instead? Like "not the de facto capital", and "seat of government" or something of the sort.

I disagree, it is merely descriptive. The point of the deck is to be useful to people navigating the world, and such descriptions are obvious and commonplace. Comparing the two as such has no negative connotation in my mind.

Now @aplaice's critique of using religion as the hint being very unique and therefore a giveaway has more merit. However, I would not like to go down the exact opposite path of having almost useless descriptions. Take Aruba and Sint Eustatius for example. Their capital hints "Constituent country" and "Special municipality" respectively are absolutely useless in my mind, as I do not and never have cared which is which in terms of their position in the Netherlands hierarchy. I still get these wrong because of this :sob: The same would happen to Palestine - Isreal if this change was made, I am sure. 

My preferred solution would be something more bland and general that has no relation to any specific country itself: **position relative to the other**. Sint Eustatius and Aruba would get the capital hints "North" and "South" respectively. Wtf does "north" mean when viewing it as a Capital hint? Well you are being given a capital hint because it could be ambiguous, and this one you are viewing now is the one that is more north than the other (generally). It gives nothing away about the country, but separates them for your brain *if you know where it is in the first place* :wink: 

So Palestine - Isreal could be East - West, respectively. Actually, looking at all the cards that currently have hints, all of them can fit into an East - West comparison (excluding UK - England, and Belgium - EU). General solution? :wink:

**Comment by jamesnelmore** [comment]
I hadn't thought of that being reductive because Israel was created for the explicit purpose of being a Jewish state, however Palestine was not (I don't think; I may be wrong about that) so I take your point. As far as location goes, the Gaza Strip means that Palestine is both east and west of Israel, so I don't think that will work. At the moment a hint related to capital status seems like the best idea.

 It may also be worth adding something about embassies in Tel Aviv in Israel's capital info field. I can open a separate issue for that if @axelboc would prefer.

**Comment by axelboc** [comment]
> It may also be worth adding something about embassies in Tel Aviv in Israel's capital info field. I can open a separate issue for that if @axelboc would prefer.

Not sure about this to be honest, but happy to discuss it in a separate issue indeed.

**Comment by jamesnelmore** [comment]
Opened  #408.

**Comment by aplaice** [comment]
> I feel it's a bit reductive to hint at a country by its dominant religion.

FWIW I also feel that way, though it's hard to explain. (Israel is indeed very much a Jewish state by design — but whether it's religious or ethnic Jewishness is another matter.  Since, according to the 1947 UN partition plan the other state (what is effectively now the State of Palestine) was supposed to be an Arab state, it's arguably ethnic Jewishness that was key.)

<hr/>

> Take Aruba and Sint Eustatius for example.

I'm quite surprised, since presumably like you, I didn't delete the "legacy deck" either, but apparently this pair of capital hints is no longer in the deck, because Sint Eustatius's (?) capital is no longer in the deck.

(We now only have England/UK and Belgium/EU.)

> as I do not and never have cared which is which in terms of their position in the Netherlands hierarchy.

Yeah, tbh neither do I...

<hr/>

> My preferred solution would be something more bland and general that has no relation to any specific country itself: position relative to the other.

I think that the idea of using geographic relations is brilliant!

In the case of Sint Eustatius and Aruba "North" and "South" would have been clearly far better than what we had.  In the case of the (also "defunct") Guadeloupe/Saint Kitts and Nevis and Norfolk Island/Jamaica pairs I'm less sure about clear superiority, since one being an independent state and the other not is more salient than precise administrative details, but I don't think it'd have been worse, either.

I particularly like it, since it forces you to link geographic information about the country with capital information about it!

One slight disadvantage is that it might require extra information (or "inline-documentation") to be placed in the card.  When a user would have, first seen, say:

```
Oranjestad

North
```

and the answer:

```
Sint Eustatius
```

it wouldn't have been obvious what the "North" was referring to — unlike the administrative statuses, which are absolute descriptors, "North" and "South" are relational and only make sense in context. We might have needed to add something like "Oranjestad is also the capital of Aruba" to the answer side. (Maybe; in any case this specific case is a moot question.)

> excluding UK - England, and Belgium - EU

A geography hint could perhaps be "larger" and "smaller", though I'm not sure if we should switch.

<hr/>

> So Palestine - Isreal could be East - West

My first reaction was that I love this!  Unfortunately, I came up with two objections:

1. Having 

   ```
   Jerusalem
   
   East/West
   ```

   would suggest that East/West are referrring to Jerusalem, rather than to the relative locations of the capitals and hence imply that East/West Jerusalem are the capitals of Palestine/Israel, which isn't really the case — both countries claim the whole of Jerusalem as their capital...  In the case of Israel it is *de facto* the case that government buildings are in West Jerusalem and some countries (e.g. [Australia](https://www.cbsnews.com/news/australia-recognizes-west-jerusalem-as-the-capital-of-israel/) explicitly recognise __west Jerusalem__ as the capital.  However, Palestine doesn't really even administer East Jerusalem and I'm afraid that by seeming to assign West/East Jerusalem, we'd be creating the false impression that there already is a neat, clean split of Jerusalem.
   
   Perhaps we could work around the city/country ambiguity, by using "to the East/West"?
   
2. Due to the Gaza Strip, Palestine's western-most point is to the west of Israel's western-most point and I think that Israel's eastern-most point is also to the east of Palestine's.


<hr/>


Summing up the various suggestions, adding some of my own and commenting with my personal opinions:


1. “officially approved only by seven countries as of 2021”/“does not control the area militarily”

    Far too specific
    
2. Jewish Country / Muslim Country

    A bit too specific
    
3. Non-muslim country / Muslim country

    I feel slightly icky, somehow.
    
4. Not a muslim majority country / Muslim-majority country

    Feels slightly less icky than 3. but I still don't feel comfortable.
    
5. Non-Arab country / Arab country

    This feels dismissive of the considerable Arab minority in Israel.
    
6. Not an Arab-majority country / Arab majority country

    I'm not sure why this doesn't feel as icky as **4**.  A bit too specific, though.
    
7. West / East

8. To the West / To the East

    Could be confusing given the peculiarities of Palestinian and Israeli geography
    
9. Larger / Smaller

    True both when comparing controlled land area and populaton, but given the fraught political situation I'm afraid this could be misinterpreted as some sort of value judgement ("Bigger ⇒ Better").

10. seat of government / not the de facto capital

    Taking @ohare93's criticism to heart I agree that that this, like the Oranjestad hints, might be too technical.

On the whole, my very, very weak personal preference would probably be **6**, but I'm not at all happy about it.

**Comment by jamesnelmore** [comment]
I think this is different from the Oranjestad issue because Israel and Palestine are better known, so even an equally technical hint would be less obscure. I also agree with @ohare93 and do not care about the Netherlands subnational island territory hierarchy, but I do care about Israel and Palestine. 

So, I think number 10 or some variation is the best option. Perhaps `Claimed and controlled` and `Claimed but not controlled`.

Then in *Capital Info* `Disputed.` and `Disputed; Ramallah is the administrative center.`.

**Comment by ohare93** [comment]
@aplaice :+1: Very good points, and I generally agree with your views on the suggestions.

As a sidenote: I do not aim to dismiss you or @axelboc's genral negative feelings towards using religion as a descriptor here. I simply do not care myself, in a more apathetic sense. If there are other better options (and religion is a bad descriptor anyways as it gives things away, as you pointed out) then we obviously should go with something else! :grin: 

@jamesnelmore 
> I also agree with @ohare93 and do not care about the Netherlands subnational island territory hierarchy, but I do care about Israel and Palestine.

And some people do not care about Israel/Palestine, myself included. This is a deck for the masses, and political facts should not be required to memorise geography.

I still believe geography should be used to distinguish geography, as describing them by anything political or cultural will make *someone* unhappy. The small issue being that these are disputed areas :sweat_smile: so it is also difficult to state objective facts. However, I think we can get away with things by just being less specific!

![image](https://user-images.githubusercontent.com/1471350/113483955-3c2d0f00-94a6-11eb-968c-4452e8303e22.png)

Take this map for instance. I still truly believe that "East and West" are the best descriptors to separate these two. Is it 100% accurate? God no. Is it useful? I believe so. Take Ireland and Northern Ireland for instance, no one will get confused which one "Northern Ireland" is simply because Ireland has land that is north of Northern Ireland (true). That is because **Northern** Ireland is generally more **Northern**. 

So how about the same for Palestine and Israel? 
1. Eastern / Western
2. Generally more Eastern / Generally more Western
3. Centre of landmass is more Eastern / Centre of landmass is more Western

As long as any of these are useful to the user, then the capital hint has done it's job.

Backup suggestions I have thought of include:
1. Short coastline / Long coastline
2. Flat southern border / Pointed southern border
3. Non-contiguous / Contiguous

**Comment by jamesnelmore** [comment]
@ohare93 
> And some people do not care about Israel/Palestine, myself included. This is a deck for the masses, and political facts should not be required to memorise geography.
I understand and generally agree with your sentiment, but by definition all borders, capitals, and flags are political, some are just not as controversial as others. The deck already uses political facts in other capital hints, so I don't feel like that's something we have to avoid. 

That being said, I really like `Non-contiguous / Contiguous`. I think its the best option brought up so far. Personally I thing `Discontinuous / continuous` fits better because in the national context, each are one thing, as opposed the 48 separate-but-adjacent contiguous American states, for example.

According to Merriam-Webster:
```
Contiguous: being in actual contact : touching along a boundary or at a point
```
and
```
Continuous: marked by uninterrupted extension in space, time, or sequence
```

**Comment by axelboc** [comment]
I get the appeal with using East/West, but I'm with @aplaice: it's too confusing that they're relative rather than absolute hints (i.e. to the East/West of.... what?) and that East and West Jerusalem are a thing.

I really like your suggestion, @jamesnelmore: `Claimed and controlled` and `Claimed but not controlled`. Those are true, objective facts, and absolute hints. Personally I really don't think they're comparable to the old Aruba/Sint Eustatius hints. I totally agree that those were clearly way too obscure and most likely not helping to distinguish the two cards...

What I also like about @jamesnelmore's suggestion is that the hints directly relate to what the user is learning when they see the cards: capitals. Users who haven't learnt the map cards yet or who may even have filtered them out of the deck, would find it very, very difficult to understand what is meant by "contiguous" or other such terms.
