### ISSUE TITLE
Remove requirements.txt

### ISSUE THREAD

**Issue by axelboc** [anki-geo/ultimate-geography#413]
There's a Dependabot alert caused by an outdated package version in `requirements.txt`. (It's up to date in `Pipenv.lock`, though.)

I've asked about this file before: https://github.com/anki-geo/ultimate-geography/pull/364/files#r550776335. Reading a bit more about dependency management in Python, it seems that `requirements.txt` is on the way out. Python even recommends `Pipenv` in [its own docs](https://packaging.python.org/tutorials/managing-dependencies/#managing-dependencies)

It seems counter-productive to have to keep `requirements.txt` up to date with `Pipenv.lock`, especially since GitHub is capable of [parsing the latter](https://github.com/anki-geo/ultimate-geography/network/dependencies) without problem:

![image](https://user-images.githubusercontent.com/2936402/114273975-a69cfc80-9a1c-11eb-8f2f-61e1efcc26b6.png)

Also, I think having the same set-up code running in the CI as the one recommended in `CONTRIBUTING.md` would make more sense. I don't believe installing `Pipenv` in the CI would impact the build time, thanks to GitHub Actions' caching system.

**Comment by ohare93** [comment]
Yes I am aware of this silly dependency alert, it is not actually an issue as Brain Brew does not use PyYaml any longer, it is just the Piplock file was mistakenly left as it is during my last update (it was very hard to get rid of it :sob:) I will get rid of it soon, when I update the repo to the latest Brain Brew (note models are in yaml now :wink:)

As for why the requirement file is there in the first place, let me just reiterate: **it is not used for dependency installation** :sweat_smile: Pipenv is used in Brain Brew, and all repos that currently use it, as the installation guide states.

So why is the requirements.txt file even there then? I was under the impression that this is what Github looks to in order to work out the dependencies of a project, and thus show the pretty dependencies / dependents view, and give us these types of warnings when things need updating. If that is not the case, and it can also look in the Pipfile, then of course we should get rid of it as it is duplication :+1: otherwise I think it serves an important function.

**Comment by axelboc** [comment]
> As for why the requirement file is there in the first place, let me just reiterate: it is not used for dependency installation 😅 Pipenv is used in Brain Brew, and all repos that currently use it, as the installation guide states.

It's used in the CI:

```
python -m pip install --upgrade pip
pip install -r requirements.txt
```

I'll open a PR.

**Comment by ohare93** [comment]
Yes, it's used in CI. But that is faster, I expect, than installing a Pipenv everytime on the PI :thinking: 

If requirements.txt is being removed, of course this should change too. If it is not, is it a big deal? :thinking: No worries either way, from me.

**Comment by axelboc** [comment]
GitHub's CI is fast. I don't think it will make a significant difference. And even if it's 2s slower, I'd much prefer that than to have to remember to keep `requirements.txt` up to date every time we update Brain Brew in the future. 😄

**Comment by ohare93** [comment]
Aha!

![image](https://user-images.githubusercontent.com/1471350/114275888-8b35ef80-9a24-11eb-83bd-44d2e2bb0cb5.png)

Okay, it seems you are right and the Pipfile can work for our needs :100: :ok_hand: that is excellent, I now fully support this and will remove the dirty requirements.txt file myself too :laughing:

**Comment by axelboc** [comment]
Sorry, my initial screenshot did not give much context. But you do have access to the dependency graph page of this repo, now, don't you? https://github.com/anki-geo/ultimate-geography/network/dependencies

**Comment by axelboc** [comment]
Looks like UG is still mentioned as a dependent of Brain Brew 🎉:

![image](https://user-images.githubusercontent.com/2936402/114276501-27f98c80-9a27-11eb-948b-4af799fb865e.png)

**Comment by ohare93** [comment]
> Sorry, my initial screenshot did not give much context. But you do have access to the dependency graph page of this repo, now, don't you? https://github.com/anki-geo/ultimate-geography/network/dependencies I made you guys owners, so crossed_fingers

Yes, I do have access. But when initially looking at your screenshot I had a brain fart and did not realise the obvious "Dependencies found in Pipfile" text right in front of me :laughing:

**Comment by axelboc** [comment]
Just realised the CI was not running on `master`. This fixes it: https://github.com/anki-geo/ultimate-geography/commit/b5f4bb39715a18fc01479820cebbace1f1df8c70
