### ISSUE TITLE
Request to add Bonaire, Montserrat, Pitcairn Islands, Tokelau

### ISSUE THREAD

**Issue by ndbroadbent** [anki-geo/ultimate-geography#430]
Hello, I've finished memorizing all the cards in the deck, and I wanted to test my knowledge with this 227 Countries And Territories quiz from Seterra: https://online.seterra.com/en/vgp/3355

There's only 4 territories in this Seterra quiz that were missing from the UG deck:

* [Bonaire](https://en.wikipedia.org/wiki/Bonaire)
* [Montserrat](https://en.wikipedia.org/wiki/Montserrat)
* [Pitcairn Islands](https://en.wikipedia.org/wiki/Pitcairn_Islands)
* [Tokelau](https://en.wikipedia.org/wiki/Tokelau)

"Aruba, Bonaire and Curaçao form the ABC islands." - https://www.wikiwand.com/en/Bonaire
The deck includes Aruba and Curaçao, so I think it would be nice to include Bonaire as well, since they're a group of 3 islands in a row, and the ABC hint is quite useful.

Also maybe it would be good to add a note that "Sahrawi Arab Democratic Republic" is also known as Western Sahara.

Some related discussions I found while searching the GH issues:

* #11
* #221

**Comment by ndbroadbent** [comment]
I think it could also be really helpful to include some of these Seterra maps for the small islands, maybe as additional map cards. I find this layout to be really helpful for learning where everything is in relation to other islands. E.g. some cards like this:

### Front:

<img width="881" alt="Screen Shot 2021-05-25 at 1 44 43 PM" src="https://user-images.githubusercontent.com/139536/119427589-604af500-bd5f-11eb-8fbb-38ec02086233.png">

### Back:

<img width="881" alt="Screen Shot 2021-05-25 at 1 45 12 PM" src="https://user-images.githubusercontent.com/139536/119427620-70fb6b00-bd5f-11eb-8dbd-cd9f8716de55.png">

### Front:

<img width="881" alt="Screen Shot 2021-05-25 at 1 45 41 PM" src="https://user-images.githubusercontent.com/139536/119427654-81134a80-bd5f-11eb-9afd-623c7a85ded7.png">

### Back:

<img width="880" alt="Screen Shot 2021-05-25 at 1 45 55 PM" src="https://user-images.githubusercontent.com/139536/119427673-8a041c00-bd5f-11eb-807c-d54c3eab123b.png">

### Front:

<img width="910" alt="Screen Shot 2021-05-25 at 1 46 35 PM" src="https://user-images.githubusercontent.com/139536/119427728-a1430980-bd5f-11eb-9da9-e3f9636227d7.png">

### Back:

<img width="904" alt="Screen Shot 2021-05-25 at 1 47 09 PM" src="https://user-images.githubusercontent.com/139536/119427768-b91a8d80-bd5f-11eb-9b8a-00de7e0ea031.png">

**Comment by aplaice** [comment]
Thanks for your detailed, well-illustrated and thoughtful comments!

<hr/>

Unfortunately (for compatibility with Seterra), we've settled on a set of criteria that exclude these four territories — we actually had them and decided to remove them. See [here](https://github.com/anki-geo/ultimate-geography/issues/306) for the extensive discussion, [here](https://github.com/anki-geo/ultimate-geography/blob/master/CONTRIBUTING.md#political-geography) for the current criteria and [here](https://github.com/anki-geo/ultimate-geography/blob/master/political-entities.xlsx) for the current spreadsheet with the filtering of entities. The motivation was that there was no particular reason to include, say, the Pitcairn Islands, but exclude, say [Saint Pierre and Miquelon](https://en.wikipedia.org/wiki/Saint_Pierre_and_Miquelon) and that the glut of tiny dependent states which most learners (rightly or wrongly :)) don't care about, was annoying and draining to learners.

The loss of Bonaire from the ABC islands is regrettable, (I remember the ABC/ACB islands by that very mnemonic), but I think that the overall criteria we had settled on make sense. We could "grandfather" Bonaire in on mnemonic grounds, but I'm not sure.

If you want then you could add in the lost territories from the "Legacy" deck [Ultimate_Geography_Legacy.zip here](https://github.com/anki-geo/ultimate-geography/releases/tag/v4.0) — you'll get maps consistent in style with the rest of the deck, that way, but it's probably easier and safer for you to just recreate the cards yourself.

<hr/>

Regarding the Pacific Island maps — it would definitely be a huge improvement and is [roughly what we're planning to do](https://github.com/anki-geo/ultimate-geography/issues/267#issuecomment-700880256), but nobody has yet had the time, yet.

Unfortunately, we can't just take Seterra's maps due to copyright concerns.

Having two maps per card is an interesting idea.

I'm not sure that Seterra's Caribbean maps are clearly better than what we already have, though.

<hr/>

In brief:

0. The criteria for inclusion of political entities are a compromise between comprehensiveness and focus, and likely won't be changed.
1. *Maybe* we could/should re-add Bonaire on the grounds that adding it makes Aruba and Curaçao easier to remember, so overall lowers the learning effort (despite adding a note!).
2. Changes to the Pacific Island maps mostly like you suggest are "in planning".
3. Perhaps we should have two maps for the Pacific Islands, at least as a stop-gap measure, if we can find/adapt (with little effort) a suitable set of maps. (If we add them for all the Pacific Islands, they won't be really "giving away" the answer.)

**Comment by ndbroadbent** [comment]
Thanks very much for your reply, that makes a lot of sense. I also appreciate the link to the Legacy deck! I wonder if there might be some other people who are interested in an "extended edition" that includes even more territories, capitals, flags, etc. I'm probably going to be adding quite a few more territories to my own deck since I've enjoyed memorizing everything so far and would like to continue. 

I've also decided to look at the [ISO 3166](https://www.wikiwand.com/en/List_of_ISO_3166_country_codes) country codes, and I want to make sure my deck covers all the countries/territories in that table. After that, I might start trying to memorize currencies and populations, etc.

Anyway, thanks a lot for your detailed reply! I've really enjoyed this deck so far, and it's really great resource!

**Comment by ndbroadbent** [comment]
OH actually it was easier to just download the apkg for version 3.3.1: https://github.com/anki-geo/ultimate-geography/releases/tag/v3.3.1

This added all of the removed cards back into my deck:

```
[Added] Galápagos Islands, Province of Ecuador., Puerto Baquerizo Moreno, , ,  ug-flag-galapagos_islands.svg , Sierra Leone (slightly lighter blue),  ug-map-galapagos_islands.png 
[Added] Bonaire, Special municipality of the Netherlands., Kralendijk, , ,  ug-flag-bonaire.svg , ,  ug-map-bonaire.png 
[Added] Ceuta, Autonomous city of Spain., , , ,  ug-flag-ceuta.png , ,  ug-map-ceuta.png 
[Added] Christmas Island, External territory of Australia., Flying Fish Cove, , ,  ug-flag-christmas_island.svg , ,  ug-map-christmas_island.png 
[Added] Easter Island, Polynesian island and special territory of Chile., , , ,  ug-flag-easter_island.svg , ,  ug-map-easter_island.png 
[Added] Melilla, Autonomous city of Spain, , , ,  ug-flag-melilla.png , ,  ug-map-melilla.png 
[Added] Montserrat, Overseas territory of the United Kingdom., Brades, Eruptions in 1997 destroyed the capital city of Plymouth, making Brades the de facto capital., ,  ug-flag-montserrat.svg , ,  ug-map-montserrat.png 
[Added] Norfolk Island, External territory of Australia., Kingston, , Not a sovereign country,  ug-flag-norfolk_island.svg , ,  ug-map-norfolk_island.png 
[Added] Saba, Special municipality of the Netherlands., The Bottom, , ,  ug-flag-saba.svg , ,  ug-map-saba.png 
[Added] Pitcairn Islands, Overseas territory of the United Kingdom., Adamstown, , ,  ug-flag-pitcairn_islands.svg , ,  ug-map-pitcairn_islands.png 
[Added] Cocos (Keeling) Islands, External territory of Australia., West Island, , ,  ug-flag-cocos_islands.svg , ,  ug-map-cocos_islands.png 
[Added] Saint Helena, Part of Saint Helena, Ascension and Tristan da Cunha, an overseas territory of the United Kingdom., Jamestown, , ,  ug-flag-saint_helena.png , ,  ug-map-saint_helena.png 
[Added] Sint Eustatius, Special municipality of the Netherlands., Oranjestad, , Special municipality,  ug-flag-sint_eustatius.svg , ,  ug-map-sint_eustatius.png 
[Added] Tokelau, Dependent territory of New Zealand. Tokelau has no official capital; the meeting place of the Tokelau Council rotates annually., , , ,  ug-flag-tokelau.svg , ,  ug-map-tokelau.png 
[Added] Mount Athos, Autonomous orthodox monastic state in northeastern Greece, also known as the Holy Mountain., Karyes, , ,  ug-flag-mount_athos.png , ,  ug-map-mount_athos.png 
[Added] British Indian Ocean Territory, Overseas territory of the United Kingdom., Camp Justice, , ,  ug-flag-british_indian_ocean_territory.svg , ,  ug-map-british_indian_ocean_territory.png 
[Added] Saint Barthélemy, Overseas territory of France., Gustavia, , , , ,  ug-map-saint_barthelemy.png 
```

<img width="717" alt="Screen Shot 2021-05-26 at 3 42 55 PM" src="https://user-images.githubusercontent.com/139536/119599404-0b7bad00-be39-11eb-8274-bb360a50a0d8.png">

Will continue adding more from the ISO 3166 country codes table!

**Comment by ohare93** [comment]
> I wonder if there might be some other people who are interested in an "extended edition" that includes even more territories, capitals, flags, etc.

There are plenty of us! :wink: :+1: I also do not want to lose any of the legacy cards, and it is my intention to add them to an "extended deck" in the future that can live alongside the original. Will probably get around to that in 6 months or so, being optimistic :smile:
