### ISSUE TITLE
Add Wa State

### ISSUE THREAD

**Issue by FrankAlbella** [anki-geo/ultimate-geography#442]
[Wa State](https://en.wikipedia.org/wiki/Wa_State) is a "de facto autonomous state within Myanmar." Similar to Bougainville, Wa State is listed under under the further information column in Myanmar in the [List of Sovereign States](https://en.wikipedia.org/wiki/List_of_sovereign_states) Wikipedia page.

**Comment by aplaice** [comment]
Bougainville island is included as an "Autonomous island". (We came to the conclusion that autonomous areas that are islands are more interesting than those that are not — in general our criteria for autonomous regions/dependent territories are geared towards regions that are also geographically "isolated" from their "parent" country, since these are likely to be more interesting and _slightly_ more likely to be referred to as distinct regions in real-world use.)

Wa state is listed in the [list of autonomous areas](https://en.wikipedia.org/wiki/List_of_autonomous_areas_by_country), but since it's not an island it doesn't pass the criteria. (If we were to include non-islands, we'd have to include many, many more such areas, if we used the same population threshold as for islands.)

We don't use the further information column in the List of Sovereign states, since it contains very diverse types of sub- (and sometimes super-)divisions, that aren't comparable with each other.

**Comment by FrankAlbella** [comment]
I see! I noticed other regions in the further information too but figured I'd start with Wa State before going through the rest, but your explanation makes sense. Is there any special reason places like Transnistria or Artsakh are included despite being landlocked that doesn't apply to Wa State?

**Comment by axelboc** [comment]
Hello! _Transnistria_ and _Artsakh_ are considered sovereign states. They are listed under "Other states" on Wikipedia's [list of sovereign states](https://en.wikipedia.org/wiki/List_of_sovereign_states).

If you're interested in the details, check out [this section](https://github.com/anki-geo/ultimate-geography/blob/master/CONTRIBUTING.md#political-geography) of the CONTRIBUTING guide. 😉

**Comment by FrankAlbella** [comment]
Oh I didn't notice the other states section, that makes a lot more sense now. Thanks!
