### ISSUE TITLE
Add a bit of context to Micronesia map (suggestion)

### ISSUE THREAD

**Issue by josealberto4444** [anki-geo/ultimate-geography#455]
The current maps of Micronesia, Melanesia and Polynesia share the context:

Micronesia            |  Melanesia            |  Polynesia
:-------------------------:|:-------------------------:|:-------------------------:
![Micronesia](https://github.com/anki-geo/ultimate-geography/raw/5c033af05369f351402a09fc7aa446d57d2b59f3/src/media/maps/ug-map-micronesia.png "Micronesia")  |  ![Melanesia](https://github.com/anki-geo/ultimate-geography/raw/5c033af05369f351402a09fc7aa446d57d2b59f3/src/media/maps/ug-map-melanesia.png "Melanesia")  |  ![Polynesia](https://github.com/anki-geo/ultimate-geography/raw/5c033af05369f351402a09fc7aa446d57d2b59f3/src/media/maps/ug-map-polynesia.png "Polynesia")

I think it is a great idea, I love it, but I just reviewed this ["new"](https://github.com/anki-geo/ultimate-geography/commit/6de32a804fd41381cd4e8ea2e236c6d866fcfb30) Micronesia map for the first time today and thought that a part of the region was cut off the image by accident. I went to the repo and looked for [the previous version of that map](https://github.com/anki-geo/ultimate-geography/raw/a82739df1fb33d45a3b412de767fb7b0dbbf8824/src/media/ug-map-micronesia.jpg) (that I did have seen before) and discovered that it wasn't an error. It's just that the region has that shape.

I know that the maps already show a very big area, but I would include a tiny bit more at the top just to reassure the user that the map is correct. A quick and dirty sketch:

Micronesia            |  Melanesia            |  Polynesia
:-------------------------:|:-------------------------:|:-------------------------:
![Micronesia](https://user-images.githubusercontent.com/13300909/129452043-c018edd0-845e-4d5c-b52a-4695fa59dda3.png "Micronesia")  |  ![Melanesia](https://user-images.githubusercontent.com/13300909/129452037-7cb57953-d2f1-4326-9324-2a6479477964.png "Melanesia")  |  ![Polynesia](https://user-images.githubusercontent.com/13300909/129452045-e72d20fa-42db-4ee0-a313-2bacb5f8c323.png "Polynesia")

However, maybe it's too much effort and it's not worth it. I don't know, because I haven't collaborated with images to this deck ever, but I'd be glad to learn how to do it. ^^

**Comment by aplaice** [comment]
You're right, this does look potentially confusing! (Interestingly the "main" Wikipedia image of [Micronesia](https://en.wikipedia.org/wiki/Micronesia) shares this problem, though it makes sense, since they're ultimately derived from the same source...)

Unfortunately, the [image on which our images are based (via a couple of [style changes with sed](https://github.com/anki-geo/ultimate-geography/pull/194))](https://commons.wikimedia.org/wiki/File:Oceania_UN_Geoscheme_Regions_with_no_text.svg) is ultimately derived from [this](https://commons.wikimedia.org/wiki/File:Oceania_ISO_3166-1.svg) which also doesn't have any further geographical context northwards (in Taiwan and China, which we probably don't want to truncate). 

One alternative might be to move the northern limit of the Micronesian shaded area slightly southwards, instead. (AFAICT the north-most part is pure ocean anyway, so we wouldn't be excluding any country or dependency. Also, I can't find a source for the precise limits of Micronesia used in the base image, so moving them slightly southwards wouldn't really be problematic.)

A second alternative would be to generate the maps from scratch, from Natural Earth Data (but from what I remember (though I might be wrong), I didn't particularly like the limits of the Pacific Island areas in Natural Earth, which is why I adapted an existing Wikimedia SVG).

**Comment by josealberto4444** [comment]
Thanks for your detailed answer! ^^

> One alternative might be to move the northern limit of the Micronesian shaded area slightly southwards, instead. (AFAICT the north-most part is pure ocean anyway, so we wouldn't be excluding any country or dependency. Also, I can't find a source for the precise limits of Micronesia used in the base image, so moving them slightly southwards wouldn't really be problematic.)

I opted for this approach. I generated the svg files and edited them. The result is the following

Micronesia            |  Polynesia
:-------------------------:|:-------------------------:
![Micronesia](https://user-images.githubusercontent.com/13300909/132094134-2e6dbec9-54b8-409c-9a0b-f9391f808572.png "Micronesia")  |  ![Polynesia](https://user-images.githubusercontent.com/13300909/132094144-b85248b5-41ce-4909-a852-9e4f586f0fa4.png "Polynesia")

I also adjusted Polynesia limits, as you can see, to have consistent margins, as there seem to be no islands in the excluded regions.

However, when I generated the PNGs, they are substantially bigger (for Micronesia, 27.1 KiB vs 18.9 KiB). How did you compress them?

**Comment by aplaice** [comment]
These look great! Thanks!

> How did you compress them?

We generally use `optipng` (available in Debian's/Ubuntu's (and probably other distros') repositories), to compress all the images. Don't worry, though, if the images end up slightly bigger!

**Comment by josealberto4444** [comment]
OK, done! They are now smaller (although a bit bigger than before).

---

In a few days I'll have seen all cards in the deck for the first time in my life (only 25 new cards remaining right now). I'd like to make use of this comment to thank you for making this really great deck. You have substantially improved my knowledge. <3
