### ISSUE TITLE
Add Gibraltar zoombox (suggestion)

### ISSUE THREAD

**Issue by josealberto4444** [anki-geo/ultimate-geography#461]
Do you think it's a good improvement for the deck? I know there is no ambiguity in this case, but right now, in my opinion, the map is too vague.

I've been taking a look to #357 to try making the zoombox for Gibraltar and see if it looks well, but I don't really know what's the procedure you followed for making these zoomboxes. Could you explain it to me, @aplaice? =)

**Comment by aplaice** [comment]
> Do you think it's a good improvement for the deck? I know there is no ambiguity in this case, but right now, in my opinion, the map is too vague.

It'd be a great improvement. You're right that the current map is pretty vague. If one doesn't already know that Gibraltar is north of the strait, then it's probably tricky to determine its precise location based on the highlighting circle...

<hr/>

The procedure I've generally followed is:

A. Try to find an existing wikimedia map following the location map scheme with an appropriate zoombox, and adapt it (colour-wise, cropping-wise\* or highlighting-wise). If that fails,

\* Most of the location map scheme maps contain a map of the entire globe, but most of it is "cropped out". Adjusting the cropping one can make the map show a different area. (I'm not sure if my description makes sense. If not, it'll hopefully be obvious what I mean if you open, say, [Gibraltar in its region](https://commons.wikimedia.org/wiki/File:Gibraltar_in_its_region.svg) in Inkscape.)

B. (I'm assuming we already have a map that shows the relevant area "in its region", only without a zoombox, like we do in this case.)
1. Find a wikimedia map that shows a close-up of the relevant area.  It might be stand-alone or a zoom-box in another map that's not suitable for our purposes. (For instance, for Mayotte, I had used a [stand-alone map of the Comoros](https://commons.wikimedia.org/wiki/File:Mahor%C3%A9_in_Comoros.svg), while for Hong Kong, I used one [with Hong-Kong in a zoom-box](https://commons.wikimedia.org/wiki/File:Hong_Kong_in_China_(zoomed)_(%2Ball_claims_hatched).svg). (For the Hong-Kong map, I could have also tried to adapt the existing zoombox map by removing the Chinese province divisions, changing the colours and adding a "mini-map" (map showing the region on the globe, in the bottom-left), but it'd have been more trouble than it was worth.))
2. Copy the close-up into the existing "in its region" map.
3. (If I'm feeling very pedantic. I don't recommend doing this...) If the projections of the close-up and main/"in its region" maps are different, find the matrix (CSS) transformation that will best transform the former onto the latter. (The idea is that I want the zoom-box to look exactly like that segment of the main/"region" map blown up, just with more detail. If the projections are different then this won't be quite the case. Obviously, this isn't essential — the point of the zoom-box is to show more detail of the geographic area, and it doesn't necessarily have to be geometrically similar to the main map!) Unfortunately, since map projections are non-linear, the transformation will be only correct to first order, but in my experience using the Jacobian at the coordinates (long., lat.) of the mid-point of the zoombox give quite good results.
4. (If necessary.) Crop the zoom-box map.
5. Add a border to the zoom-box map. (The colour I used, trying to emulate the locator maps conventions — unfortunately, they're not all completely consistent — was `#6A6968`.)
6. Add a shadow to the zoom-box map. (Again trying to follow the conventions, I used `#6A6968` with opacity `0.5`.)
7. Add a bounding box in the main map around the area that's being zoomed into. (I used `#C12838`.) (Unless you're being super-pedantic, you can do it by eye.)
8. Add a "zoom-trail" between the bounding box and the zoom box. (I used `#C12838` with opacity `0.2`.)


<hr/>

In the case of Gibraltar, the key question is what zoom level is desired in the zoom-box. IMO the most important ambiguity is whether Gibraltar is in Europe or Africa, and hence a zoom-box with an excessive zoom, just showing the peninsula would not be too helpful (e.g. I'd prefer something approximately like [this](https://commons.wikimedia.org/wiki/File:Location_Gibraltar_EU.svg), [this](https://commons.wikimedia.org/wiki/File:EU-Gibraltar.svg) or even [this]([this](https://commons.wikimedia.org/wiki/File:Gibraltar_and_European_Union_(zoomed).svg)), over [this](https://commons.wikimedia.org/wiki/File:Gibraltar_location_in_Europe.svg)).  However, I may well be wrong, and in any case, you're (considering — no pressure!) doing the work, so it's up to you to decide — any zoom-box would be a great improvement! :)

<hr/>

Having casually looked at some of the existing Wikimedia maps, if I were doing this, I'd probably try to adapt [this map](https://commons.wikimedia.org/wiki/File:Gibraltar_in_United_Kingdom.svg) (approach A.).

1. The zoom-box is IMO _slightly_ too zoomed out, but given the above argument slightly too zoomed out is IMO better than slightly too zoomed in, so IMO it's acceptable.
2. Unlike in our [existing Gibraltar in its region map](https://commons.wikimedia.org/wiki/File:Gibraltar_in_its_region.svg), Gibraltar isn't geographically centred, but that can be relatively easily adjusted by changing the cropping.
3. The colours could be trivially changed so that everything (and not just the UK) is pale yellow/light latte (whatever is the name of that colour).
4. Otherwise the map already follows our style conventions.

(This is just a suggestion, you may find something better or choose a completely different approach! :))

**Comment by josealberto4444** [comment]
Thank you very much, you helped me a lot!

I opted for the approach B, using [the last map you said](https://commons.wikimedia.org/wiki/File:Gibraltar_in_United_Kingdom.svg) but with a different zoom for the zoom-box (given by [this map](https://commons.wikimedia.org/wiki/File:Gibraltar_and_United_Kingdom_(zoomed).svg)). Here is the (provisional) result in high resolution:

![Gibraltar_in_its_region_(zoom)_before_clipping svg](https://user-images.githubusercontent.com/13300909/132146331-53dd81e2-b1d7-4a35-966e-2dee84948765.png)

I think I followed all steps (except B.3, I'll talk about that in a moment). If I missed something or you have more suggestions (is it a good zoom level?), I'm completely open. ^^

About step B.3: I understand everything that you said, but the problem for obtaining the Jacobian of the transformation is that I don't know its expression (I don't know which transformations exactly are the maps using). I'd like to fix it, because I don't like the fact that the strait looks so different in the big map and the zoom-box (seems to be rotated and skewed). I haven't searched which projections are usual on maps, I'm asking you first, in case you have more expertise with this and directly know the answer or can guide me more than just learning from scratch about all map projections and knowing how to identify them. =P

**Comment by aplaice** [comment]
Wow! That's fantastic! :) I really like the fact that one can also clearly see Ceuta! (Despite knowing their locations, I had somehow never realised that the two were almost perfectly opposite each other!)

Once you're happy with the map, I'd recommend uploading it to Wikimedia, as, say, "Gibraltar in its region (zoom)"!

> I think I followed all steps (except B.3, I'll talk about that in a moment). If I missed something or you have more suggestions (is it a good zoom level?), I'm completely open. ^^

IMO it's perfect! @axelboc might have some feedback as he has a better instinct for optimal arrangement of elements than I do.

<hr/>

> About step B.3: I understand everything that you said, but the problem for obtaining the Jacobian of the transformation is that I don't know the expression of the transformation (I don't know which transformations exactly are the maps using). I'd like to fix it, because I don't like the fact that the strait looks so different in the big map and the zoom-box (seems to be rotated and skewed). I haven't searched which projections are usual on maps, I'm asking you first, in case you have more expertise with this and directly know the answer or can guide me more than just learning from scratch about all map projections and knowing how to identify them. =P

Yeah, I get that feeling of being annoyed by the discrepancy! :)

I usually just follow the trail of sources on Wikimedia back to the original and hope that they mentioned the projection used.

In the case of the "X in its region.svg" maps (that we use as the main map for virtually everything), they all use the [Winkel tripel projection](https://en.wikipedia.org/wiki/Winkel_tripel_projection), with the "default" value of `\phi_1` (`\arccos(2/\pi)$` — approx. 50°28'). This is also the case for the [Gibraltar in UK map](https://commons.wikimedia.org/wiki/File:Gibraltar_in_United_Kingdom.svg).

For the [Gibraltar and United Kingdom (zoomed)](https://commons.wikimedia.org/wiki/File:Gibraltar_and_United_Kingdom_(zoomed).svg) map (for the zoom-box), I think that the zoombox uses the same projection as the main map, there. The main map seems to be ultimately derived from [this](https://commons.wikimedia.org/wiki/File:Europe_laea_location_map.svg), which uses the [Lambert azimuthal equal-area projection](https://en.wikipedia.org/wiki/Lambert_azimuthal_equal-area_projection), with the values of the parameters given [here](https://en.wikipedia.org/wiki/European_grid). (I _think_ that the important parameters are the latitude and longitude of the projection centre (52° N, 10° E) and that the false easting and false northing are just additive constants. I _think_, but I'm less confident, that they (52° N, 10° E) are just the standard parallel (`\phi_1`) and central longitude (`\lambda_0`) from the set of formulae [here](https://mathworld.wolfram.com/LambertAzimuthalEqual-AreaProjection.html).)

Just in case this isn't obvious: when finding the Jacobian between the two projections, I recommend calculating the Jacobians to and from the [equirectangular projection](https://en.wikipedia.org/wiki/Equirectangular_projection) (i.e. where x=longitude, y=latitude) and using their product (instead of trying to find a closed formula linking the two target projections, and obtaining the Jacobian from that...).

<hr/>

> just learning from scratch about all map projections and knowing how to identify them

This might actually make an interesting Anki deck. :D (It's one of the many things that I'd like to do if I had more time and energy...)

**Comment by josealberto4444** [comment]
I don't have too much time right now, but I'll take care of this in a few weeks. ^^

**Comment by josealberto4444** [comment]
I think I did it! Take a look and tell me if you find anything strange (in the projection or wherever), @aplaice. I did all the calculations with sympy and can redo them with little effort, in case you think there is a mistake. Thanks a lot for all your help, I've learned a lot in the process.

What do you think about the zoom level, @axelboc?

![Gibraltar_in_its_region_(zoom)](https://user-images.githubusercontent.com/13300909/149858978-d5902b66-0da9-4d8e-98ec-6dbe54006219.png)

> Just in case this isn't obvious: when finding the Jacobian between the two projections, I recommend calculating the Jacobians to and from the [equirectangular projection](https://en.wikipedia.org/wiki/Equirectangular_projection) (i.e. where x=longitude, y=latitude) and using their product (instead of trying to find a closed formula linking the two target projections, and obtaining the Jacobian from that...).

It should have been obvious, but it's been a long time without dealing with non-linear transformations, so thanks for telling me that, at first I was going to do it the hard way, hahaha.

> This might actually make an interesting Anki deck. :D (It's one of the many things that I'd like to do if I had more time and energy...)

Let me know if you do it, I'd be very interested. ^^

**Comment by axelboc** [comment]
The zoom level is perfect, nice job! :raised_hands:

**Comment by aplaice** [comment]
This looks fantastic! Thanks!

The file changes wouldn't overlap with those of the Chinese translation, so I think that we could (and should! :)) include this asap.

**Comment by josealberto4444** [comment]
Thank you all! =)

I spotted a mistake in the calculation, so this is the final result (the previous one seemed to be a bit stretched to the sides, so I was a bit suspicious about it):

![Gibraltar_in_its_region_(zoom)](https://user-images.githubusercontent.com/13300909/149936514-3de988a7-e833-46e6-b2d6-c369a3a227c5.png)

I'll make a PR later today. ^^

**Comment by josealberto4444** [comment]
> Once you're happy with the map, I'd recommend uploading it to Wikimedia, as, say, "Gibraltar in its region (zoom)"!

I need some help with this. =P

When I use the (standard/default) uploader, it asks me about _one_ file from which the file I'm uploading is derived. However, this is not the case, as the map I'm uploading derives from two maps. I've seen that [you managed to indicate that](https://commons.wikimedia.org/wiki/File:Comoros_in_its_region_(zoom).svg), how did you do it? Just editing the page after uploading it or there is a way of doing it right from the beginning?

**Comment by josealberto4444** [comment]
OK, I copied the wiki code in that page in the uploader source and authors and it just worked, so [it is now published](https://commons.wikimedia.org/wiki/File:Gibraltar_in_its_region_(zoom).svg)! ^^

**Comment by aplaice** [comment]
Yes, it's very far from obvious, but you can paste wikitext in the upload textboxes!

Thanks again! :)
