### ISSUE TITLE
Distinguish Sint Maarten from Sint-Maarten in Dutch

### ISSUE THREAD

**Issue by aplaice** [anki-geo/ultimate-geography#464]
In Dutch, the names of Sint Maarten (constituent country of the Kingdom of the Netherlands) and Saint-Martin (French overseas collectivity) are [Sint Maarten](https://nl.wikipedia.org/wiki/Sint_Maarten_(land)) and [Sint-Maarten](https://nl.wikipedia.org/wiki/Sint-Maarten_(Franse_Antillen)) respectively.

This is obviously not identical but still confusingly similar.

I'd suggest following the approach we've used to distinguish the two in languages where they're identical (e.g. Saint-Martin in French) and adding a disambiguating parenthetical.

For instance:

```
Sint Maarten (Koninkrijk der Nederlanden)
Sint-Maarten (Frankrijk)
```
or closely clinging to Wikipedia:

```
Sint Maarten (land)
Sint-Maarten (Franse Antillen)
```

<hr/>

If somebody wants to train themself to distinguish the two by the lack of the hyphen (tbh I can imagine a school teacher requiring students to do that...), then they can remove the parenthetical.

(Noticed while reviewing the Russian fixes.)

<hr/>

@WouterVdS If/when you have time (this isn't urgent! :)):

Do you think that this makes sense, and if so, would either of the above pairs be suitable?

**Comment by axelboc** [comment]
Well spotted 👍 

- For French Sint-Marteen, I'd suggest sticking with the disambiguation text from Wikipedia like we did for other languages: `Sint-Maarten (Franse Antillen)`.
- However, since Dutch is obviously the language of the kingdom of the Netherlands, I think Dutch Sint Marteen _does not_ need any disambiguation text. I reckon Dutch people will simply assume the card is about Dutch Sint Marteen, even if they know about French Sint Marteen.

**Comment by aplaice** [comment]
> For French Sint-Marteen, I'd suggest sticking with the disambiguation text from Wikipedia like we did for other languages: Sint-Maarten (Franse Antillen).

Makes sense! I'll use that!

<hr/>

> Note that this would then make Saint-Martin (Antilles françaises) in French inconsistent smile -- but maybe the reasoning still holds? If not, never mind ^^

I'm not sure. AFAIK the Kingdom of the Netherlands is the only country/set of countries with Dutch as its official language. In contrast, there are quite a few countries with French as an official language. For somebody from, say, Belgium or Cameroon, Sint Maarten and Saint-Martin are both about as alien and unknown, so I don't think the analogy quite holds.

<hr/>

However, I'm not quite convinced that the reasoning holds even for Dutch. After all, Sint Maarten is a far-off sort-of dependent state, that many Dutch people might not know about (unfortunately, I don't have any statistics), so won't necessarily assume it as a default.

Also, even if it were well-known, it might still be useful to keep the parenthetical in both cases, for clarity. The best comparison that I can think of is if we had both Georgia the US state and Georgia the country — in which situation I'd be in favour of having disambiguations for both.

<hr/>

The question then remains, though, what do we use as the disambiguation. `(Land)` ("country"?) IMO isn't perfect...

**Comment by axelboc** [comment]
Yeah you're right. Not sure either, then, but I think I'd be more in favor of `(Koninkrijk der Nederlanden)` than `(land)` that's for sure.

Interestingly, in Czech, the translation uses the equivalent of "(Dutch part)" and "(French part)", as in "the Dutch/French part of the island". In fact, the term "part" is used in the introductions of the Wikipedia articles in various languages, so it has some weight to it. The downside is that "part" is a qualifier for the island of Saint Martin rather than for the two political entities, if you see what I mean. But perhaps that's not a huge deal -- perhaps it even makes it clearer that they are both parts of the same island? If so, then we might be able to use this scheme for both French and Dutch as well.
