### ISSUE TITLE
New cards not added when upgrading to v5.0 using a very old version of Anki

### ISSUE THREAD

**Issue by josealberto4444** [anki-geo/ultimate-geography#481]
I'm trying to upgrade the Spanish Extended deck. I'm pretty sure I'm starting from v4.1.1, but just in case, I ran the check. Unfortunately, I got an error:

```
Traceback (most recent call last):
  File "/usr/share/anki/aqt/main.py", line 1214, in onDebugRet
    exec(text)
  File "<string>", line 5, in <module>
TypeError: object of type 'sqlite3.Cursor' has no len()
```

It could be that my OS is using an old version of python, or an old version of Anki, or both, but I don't know how to solve this. CrowdAnki is updated.

Anki 2.1.8 Qt 5.11.3 PyQt 5.11.3
Python3 3.7.3
Python 2.7.16
I'm (unfortunately) using PureOS right now and they seem to still use Python 2 :_(

So I went on and just assumed that I was using 4.1.1, because I remembered looking at that strange version number when installing, so I'm confident in having it. I tried to import it, and the program said that the import was successful, but there are no new cards. I don't have the cards of the new seas (however, images for cards already existent are updated). How can I check what's happening?

**Comment by aplaice** [comment]
:(

Anki 2.1 uses Python3 (I don't think it's even possible to force it to use Python2), so the presence of Python2 isn't a problem.

The old version of Anki (presumably the version packaged with PureOS?) is probably the reason why the "investigative" console script snippet failed. (Presumably Anki's internal SQL interface was slightly different.) If the images of the already existing cards were successfully updated, though, then it seems that you probably didn't have the wrong GUIDs from 4.1.0, further supporting that you have 4.1.1, like you remember.

Hence, the main issue is the partially successful CrowdAnki import.

Testing with Anki 2.1.9 (Anki's [archive](https://apps.ankiweb.net/downloads/archive/) doesn't have Anki 2.1.8) I can indeed reproduce the issue — the existing cards are all updated (e.g. Romania in the flag similarity for Chad is now spelled "Rumania" rather than "Rumanía" as it had been in 4.1.1), but none of the new cards are added.

I suspect the issue is the old version of CrowdAnki — according to Anki/AnkiWeb, the version of CrowdAnki that you have is the "latest", but it's actually a pretty old version (the latest version of CrowdAnki available for Anki 2.1.0-2.1.25 was updated in 2020-06-15). 

I'll look into whether the issue is something that can be easily solved with a simple patch of the old version of CrowdAnki.

**Comment by aplaice** [comment]
I think that the issue is somewhere in `Note.save_to_collection` (in `representation/note.py`) — the error occurs when adding a note with an existing (rather than a newly created) note_model. I'm not 100% sure about the proper code fix, yet.

However, a practical fix is to open the browser (with key `b`), select the "Ultimate Geography [Extended]" note model (from the side bar or by pasting `"note:Ultimate Geography [Extended]"` into the search bar), selecting one of the existing notes and pressing <kbd>Ctrl</kbd><kbd>l</kbd> to enter the note model editor. The cards associated with the new notes should now magically appear! :) 

(The issue is that the notes are all actually added, but without any cards. Entering the note model editor forces Anki to regenerate all the cards associated with the given note model, resulting in the new notes getting their associated cards...)

**Comment by josealberto4444** [comment]
It worked! :_)

Thank you very much for taking time to investigate it. <3
