### ISSUE TITLE
Add Chinese Version

### ISSUE THREAD

**Issue by ruin1990** [anki-geo/ultimate-geography#493]
Hi, how can I contribute to a Simplified Chinese version with ultimate-geography?
Shall I modify the ultimate-geography/src/data/*.csv ? And add a new column for xxx:cn?
And I'll be appreciated if someone can provider me a method to do this.

**Comment by aplaice** [comment]
Thank you very much for the offer! A Chinese version of Ultimate Geography would be very welcome!

> Shall I modify the ultimate-geography/src/data/*.csv ? And add a new column for xxx:cn?

Yes, please modify the `src/data/*.csv` files! However, I think that the language code for Chinese is `zh`, not `cn` (`cn` is the code for the country, not the language). 

I _think_ that we should aim to only have one Mandarin Chinese deck (i.e. not have one using Traditional characters and one using Simplified) and that it should use Simplified characters (due to the huge population disparity). Hence, I think that it's not worth using the disambiguation code (`zh-Hans`).

(I may very well be wrong — if you disagree then please say so.)

<hr/>

>  And I'll be appreciated if someone can provider me a method to do this.

You could open the CSV files in a spreadsheet (e.g. Libreoffice Calc, Microsoft Excel or Google docs), add the columns and fill in the relevant fields.

Alternatively, you could translate the English deck "in place" (within Anki), export the translated deck (using CrowdAnki) and use BrainBrew to convert the CrowdAnki JSON to CSV (you'd then need to rename and move around the columns (or ask somebody else to do it — I'd be happy to)). If you need further details about this method, please ask!

(From what I know, most translators chose the former method — adding the columns in a spreadsheet program and filling in the translation there.)

**Comment by ruin1990** [comment]
Thanks for your answer. I'm going to try these methods what you said. : )

**Comment by ruin1990** [comment]
hi, I have a question with guid.csv, shall I generate it?
If it is also a translation task, how can I generate it?

**Comment by aplaice** [comment]
> hi, I have a question with guid.csv, shall I generate it?

`guid.csv` will be automatically generated when you run `pipenv run brain_brew recipes/source_to_anki.yaml`, but don't worry about it.

**Comment by ruin1990** [comment]
> 

okay, and I have another question. 
There are some countries or cities whose names are transliterated in Chinese, which is a bit difficult to understand in Chinese. 
I want to bring the original English text after the Chinese language, so that the deck learners can understand something easily like this:

South Africa has no legally defined capital: the branches of government are split over three cities: Pretoria (executive), Cape Town (legislative) and Bloemfontein (judicial).
南非没有法定首都，政府部门分为三个城市：行政首都（中央政府所在地）为比勒陀利亚(Pretoria, 现名茨瓦内Tshwane)，立法首都（议会所在地）为开普敦(Cape Town)，司法首都（最高法院所在地）为布隆方丹(Bloemfontein)
Of course, I checked the information when translating to the South African capital and found that Pretoria seems to have a new name Tshwane (not yet applied)

And I think this can be achieved by modifying the template‘s’ modification

**Comment by aplaice** [comment]
Yeah, including the original English makes a lot of sense, if the transliterations might be confusing. This might become far trickier, when the original language isn't English and the English version is itself a (sometimes dubious) transliteration. (e.g. [Laayoune](https://en.wikipedia.org/wiki/Laayoune)). OTOH it might be the case that it's become conventional to include the English version, in general, in Chinese. I'll defer to your knowledge/awareness!

<hr/>

> Tshwane

I'm not convinced that we should include it. The name change has been mooted since 2005, but hasn't been implemented and might not ever be.

<hr/>

> And I think this can be achieved by modifying the template‘s’ modification

That would be the most reliable and the most convenient, but I don't think that it's currently possible with BrainBrew, at least not in cases where there are multiple capitals and we want the text in the cards structured as `Chinese1 (English1), Chinese2 (English2)` (which is what you suggested and which looks nice) rather than `Chinese1, Chinese2 (English1, English2)` (which looks less worse).

**Comment by ruin1990** [comment]
> I'm not convinced that we should include it. The name change has been mooted since 2005, but hasn't been implemented and might not ever be.
Thanks, I will revise this description. The reason why I have to add Tshwane's description is that I found that some Wikis in China have not updated this part, which is just a supplement.
I will add the following sentence to replace the original description:
Since 2005, the discussion has been changed to Tshwane, but it has not been implemented so far.

**Comment by ruin1990** [comment]
@aplaice I have some issues with brain brew. [#498 ](https://github.com/anki-geo/ultimate-geography/issues/498)
Can you help me with your convenience?

**Comment by ruin1990** [comment]
I found src/headers/desc.html only have a English version.
May I modified the yaml to add Chinese version desc_zh.html.

**Comment by ohare93** [comment]
Sure. We don't currently do that, but I think that's a good initiative to eventually do for all the languages 👍 

You'll just need to remove `default header` from the the `default_crowd_anki_gen` reference https://github.com/anki-geo/ultimate-geography/blob/3d1bbf6fa75136cd80d55b70d507f691dc874f07/recipes/source_to_anki.yaml#L304 and individually put it in each of the `generate_crowd_anki`s below that. Then you can add a new part above for the Chinese deck headers, and replace the Chinese one with a reference to that :+1:

**Comment by ruin1990** [comment]
> Sure. We don't currently do that, but I think that's a good initiative to eventually do for all the languages 👍
> 
> You'll just need to remove `default header` from the the `default_crowd_anki_gen` reference
> 
> https://github.com/anki-geo/ultimate-geography/blob/3d1bbf6fa75136cd80d55b70d507f691dc874f07/recipes/source_to_anki.yaml#L304
> 
> and individually put it in each of the `generate_crowd_anki`s below that. Then you can add a new part above for the Chinese deck headers, and replace the Chinese one with a reference to that 👍

Sure, but I found a encoding issue now. [brain-brew #39](https://github.com/ohare93/brain-brew/issues/39)
I think I can submit the translated content first, the encoding of desc.html.
Then open another issue for everyone to discuss
