### ISSUE TITLE
How to translate the template

### ISSUE THREAD

**Issue by ruin1990** [anki-geo/ultimate-geography#504]
Is there a way to translate the template so that the English in the template becomes the corresponding language?
I tried to add a folder ```src/note_models/templates_zh``` , but I don’t know how to configure it to the corresponding language through ```recipes/*.yaml```
If I modify it directly, it will cause other languages ​​to change, which may not be universal enough.

**Comment by ohare93** [comment]
There is no current way to easily translate the note model templates or the fields themselves. I understand your desire to do so, but think it might not be worth the effort.

If I was going to do it, I would just make a copy of the note model entirely, change everything, then make specific recipe events for Chinese.
1. A new `note_model_from_html_parts` for your new note model files. (This will be easier when upgrading Brain Brew to latest, as it will just be one task and not several templates too)
2. New `notes_from_csvs` using the new note_model. Remember to map the fields correctly if they are translated.
3. Use your new note model in the Chinese `generate_crowd_anki`, rather than the one used by `default_crowd_anki_gen`.

Pretty sure it is as simple as that. The issue here is just that it will remove all reusability in the recipe tasks :cry: 

I hope to improve this in Brain Brew in the future, to just insert direct translations of fields and replacement of templates.

**Comment by ruin1990** [comment]
Indeed, support on brain-brew is the best.
I think it’s really not that necessary.
 In fact, there are only 5 places that need to be translated: Flag,  Captial, Map, Location and "is similar to".
Let us focus on other more important tasks first

**Comment by melissis** [comment]
Wild suggestion: replace template text with emoji: 📍🏛️💡🏳️

No, actually, that would not work well with flag similarity. 

❕🚫🔀
(warning, do not mix up with)

I guess we could make our own symbol, but it'd be difficult to come up with a non-ambiguous symbol for that.

<details>
<summary>Details</summary>

![230px-Disambig svg](https://github.com/anki-geo/ultimate-geography/assets/116532973/96db711b-8ad5-4473-862a-b3e5e6551616)

</details>

Anomie's disambiguation symbol on Wikipedia.
