### ISSUE TITLE
A Yellow Sea bug and a request to add Bohai Sea

### ISSUE THREAD

**Issue by ruin1990** [anki-geo/ultimate-geography#519]
I found that the map of the Yellow Sea in Deck was wrong, it included the Bohai Sea. In fact, the Bohai Sea and the Yellow Sea are two different seas, and the color and composition of the sea water are also different.

I want to help correct this problem, but I don't know how to draw the map in Ultimate Geography. 
@aplaice @ohare93,  can you help it?

Map for Yellow Sea From Ultimate Geography
![ug_yellow_sea](https://github.com/anki-geo/ultimate-geography/blob/master/src/media/maps/ug-map-yellow_sea.png?raw=true)

Map for Bohai Sea from wiki：
![bohai_sea](https://upload.wikimedia.org/wikipedia/commons/6/67/Locatie_Bohaizee.PNG)
Map for Yellow Sea from wiki：
![yellow_sea](https://upload.wikimedia.org/wikipedia/commons/8/8f/Locatie_Gele_Zee.PNG)

Reference: 
https://en.wikipedia.org/wiki/Bohai_Sea
https://en.wikipedia.org/wiki/Yellow_Sea
https://zh.wikipedia.org/wiki/%E9%BB%84%E6%B5%B7
https://zh.wikipedia.org/wiki/%E6%B8%A4%E6%B5%B7

**Comment by aplaice** [comment]
Thanks for the bug report.

However, according to all the English-language sources I could find, the Bohai Sea is part of the Yellow Sea.

> The innermost bay of northwestern Yellow Sea is called the [Bohai Sea](https://en.wikipedia.org/wiki/Bohai_Sea) ([Wikipedia article on the Yellow Sea](https://en.wikipedia.org/wiki/Yellow_Sea))

> It is the northwestern and innermost extension of the [Yellow Sea](https://en.wikipedia.org/wiki/Yellow_Sea), ([Wikipedia article on Bohai Sea](https://en.wikipedia.org/wiki/Bohai_Sea)

> The Yellow Sea [...] includes the Bo Hai and Liadong Hai ([IHO 2002 draft](http://wiki.geosys.ru/lib/exe/fetch.php/ru/portal/lib/iho/s23.los.ed4draft.2002.pdf#page=164)

[IHO 1953](https://epic.awi.de/id/eprint/29772/1/IHO1953a.pdf#page=33) doesn't mention Bohai Sea.

Looking at the Wikipedia page on Bohai Sea in Chinese through google translate it looks like there are two views on whether Bohai Sea is part of the Yellow Sea...

It may well be the case that from a marine geography point of view (sediments, composition) it would make sense for Bohai Sea not to be considered part of the Yellow Sea, but I can't really judge that.  Since we're generally following the [IHO 2002 draft](https://github.com/anki-geo/ultimate-geography/blob/master/CONTRIBUTING.md#marginal-seas) I don't think we should exclude Bohai Sea from the Yellow Sea, in the Yellow Sea map.

Bohai doesn't fit the criterion of sufficient area ([see the spreadsheet](https://github.com/anki-geo/ultimate-geography/blob/master/physical-entities.xlsx), which is why it's not [slated to be added](https://github.com/anki-geo/ultimate-geography/issues/386). 

The idea for the criterion is that there are more than 100 seas and adding all of them would likely overwhelm users of the deck.  However, given that Bohai probably has greater cultural/economic/political importance than, say, some random sea in the Arctic, north of Siberia or Canada, due to the greater population density in the vicinity, it _might_ be worth adding it anyway, though I'm not convinced.  (We'd then have to revisit some more of the subseas of the Mediterranean and the many seas around the Philippines...)

Here are two maps of Yellow Sea without Bohai and Bohai by itself, in case you want to use them:
![Bo_hai_sea](https://user-images.githubusercontent.com/16461345/153894397-4a9347d3-285c-4bda-8226-3f06eefc5d2d.svg)
![Yellow_Sea_in_its_region_without_bo_hai](https://user-images.githubusercontent.com/16461345/153894404-f86fb52a-61c1-479f-9192-cab9653d8342.svg)

(It's a matter of changing the colours of a couple of SVG elements in:

https://upload.wikimedia.org/wikipedia/commons/9/9d/Yellow_Sea_in_its_region.svg )

**Comment by ruin1990** [comment]
Thanks a lot.
It is true that ROC's statement is controversial with the mainstream view. At present, PRC is still considered to be separate. At least I have checked most of the current Chinese materials.
I think the final point of this is that the two seas can be clearly seen on the side of the dividing line. The color of the sea water in the two seas is inconsistent. Amazing, it is a magical sight.
![cc](http://p1-q.mafengwo.net/s14/M00/EF/3D/wKgE2l1NC4KAfrl3AA0i3fKEopM73.jpeg)
I personally think that we can still change to a statement that is consistent with the mainstream views in Chinese Wikipedia. that separates the Bohai Sea and the Yellow Sea.
What do you think?  If it's ok, I'm ready to PR

**Comment by ruin1990** [comment]
I also find a bug with Yellow Sea.
In file country_info.csv line 87:
Yellow Sea,,,,,,,,,Kallas Västhavet i Nord- och Sydkorea.,,
I used google translate and found that he said: North Korea and South Korea call it North Sea.

In fact, ancient China called the Bohai Sea the North Sea.
Then I checked Wikipedia and found that South Korea and North Korea actually call the Yellow Sea the West Sea.
https://zh.wikipedia.org/wiki/%E9%BB%84%E6%B5%B7

Maybe we should fix this embarrassing mistake, because it wouldn't be nice if it was the North Sea that would make it seem like Korea used to be part of ancient China(Although it seems to be true)

**Comment by aplaice** [comment]
> The color of the sea water in the two seas is inconsistent. Amazing, it is a magical sight.

That's fascinating, thanks!

> Let's add a description to the bottom of the Yellow Sea. The Bohai Sea is also a part of the Yellow Sea?

We could do something like that (maybe "Bohai Sea is usually considered a part of the Yellow Sea"?). OTOH if we won't have a separate Bohai Sea note, then people would be confused what Bohai Sea is...

We could also in principle have the Yellow Sea map have Bohai Sea "hatched", but that feels overkill.

>  Yellow Sea,,,,,,,,,Kallas Västhavet i Nord- och Sydkorea.,,
> I used google translate and found that he said: North Korea and South Korea call it North Sea.

[Väst](https://en.wiktionary.org/wiki/v%C3%A4st) is definitely "west" in Swedish. I'm not 100% sure why google is translating "Västhavet" as "North Sea", but IMO it's definitely wrong. Maybe because in Danish, one of the names of the [North Sea is Vesterhavet](https://da.wikipedia.org/wiki/Nords%C3%B8en) and google translate is getting confused??

**Comment by ruin1990** [comment]
> [Väst](https://en.wiktionary.org/wiki/v%C3%A4st) is definitely "west" in Swedish. I'm not 100% sure why google is translating "Västhavet" as "North Sea", but IMO it's definitely wrong. Maybe because in Danish, one of the names of the [North Sea is Vesterhavet](https://da.wikipedia.org/wiki/Nords%C3%B8en) and google translate is getting confused?? (In Swedish the North Sea is just [Nordsjön](https://sv.wikipedia.org/wiki/Nordsj%C3%B6n).)

Your explanation has made me more knowledgeable. It seems that this comment is correct. Google translate has overturned this time. 😂

> The northwestern part of the Yellow Sea, Bohai Sea, is sometimes considered to be a separate sea
I'm not sure about the English deck, but I'm definitely in favour of adding such a description to the Chinese deck.

I agree very much, because the Bohai Sea and the Yellow Sea are separated in our Chinese geography textbook. If we don't explain it, it may be confusing.

One more question, can I add a single card to Bohai Sea?

**Comment by aplaice** [comment]
> One more question, can I add a single card to Bohai Sea?

I'm a bit hesitant, as described above. 

If we add it, then why shouldn't we also add, say [Flores Sea](https://en.wikipedia.org/wiki/Flores_Sea), the [Balearic Sea](https://en.wikipedia.org/wiki/Balearic_Sea), the [Gulf of Mannar](https://en.wikipedia.org/wiki/Gulf_of_Mannar) or the [Gulf of Tonkin](https://en.wikipedia.org/wiki/Gulf_of_Tonkin)?  The former two have an area greater than Bohai Sea (and relatively large populations near them), the Gulf of Mannar also has a very large population clustered around it, while the Gulf of Tonkin is both larger than Bohai Sea and also has a very large population clustered near it. OTOH none of them has _quite_ such a large population in their vicinity as Bohai Sea (~ 210 million people according to Wikipedia). (Population near the sea is a vaguely objective (if slightly fuzzy and hard to determine — how deep inland do we go?) indicator of how "interesting" the sea is.)

i.e. I'd very strongly prefer to have some further, easily-determinable general criterion that would help us rule that Bohai Sea (and seas U, V and W) should be included, but seas X, Y and Z excluded.  (We already have general criteria for inclusion of seas that were reached after a long discussion (#346), mainly based on area, but obviously if there were a very good argument to modify them, we could.)

<hr/>

A second option would be to only add it to the Chinese deck, but in that case there'd be an argument to (for example) add the Balearic Sea or the Alboran Sea to just the Spanish deck... Also, this is supposed to be a general interest geography deck not "general interest + local areas" geography deck.

<hr/>

A third option would be to have a deck containing the seas that are excluded from the "Ultimate Geography" (and aren't slated for inclusion).

A fourth option would be to have a Chinese-focused geography deck!

<hr/>

Overall, I'm against option **2** and leaning towards no for option **1**. Sorry!

**3** and **4** would be nice to have anyway, but *likely* won't happen in the near future.

@axelboc any thoughts/opinions?

**Comment by axelboc** [comment]
I completely agree with your assessment, @aplaice. I'm against adding a card to a specific deck and against including the sea without changing the criteria. Nearby population seems like a useful criterion for gulfs and such, but as you said, difficult to define precisely and get accurate data on.

In the short term, I'm totally open to adding a sentence to the Yellow Sea note in the Chinese deck, in the _Country info_ field, to mention that Chinese people typically don't consider the Bohai Sea to be part of the Yellow Sea.

**Comment by ruin1990** [comment]
Thank you for discussing this issue. @axelboc @aplaice 
Do you have any comments on the notes on the Yellow Sea?
My first draft looks like this:
渤海(Bohai Sea)在国际上普遍被认为是黄海(Yellow Sea)的一部分，在中国则普遍认为二者分别属于独立的海域。

In fact, I shared the deck with a few friends and they all asked where Bohai Sea went, I think at least I can find it.

**Comment by axelboc** [comment]
Great wording. I would maybe just turn the sentence around like we do in some capital info notably. Something along the lines of: "While the Yellow Sea is generally considered to include the Bohai Sea internationally, they are typically considered as two separate seas in China."

**Comment by ruin1990** [comment]
OK, I'll change it like this @axelboc @aplaice 

> While the Yellow Sea is generally considered to include the Bohai Sea internationally, they are typically considered as two separate seas in China.

虽然国际上普遍认为黄海(Yellow Sea)包括渤海(Bohai Sea)，但在中国，它们通常被视为两个独立的海域。
