### ISSUE TITLE
Aral Sea no longer exists?

### ISSUE THREAD

**Issue by ohare93** [anki-geo/ultimate-geography#535]
A random meme led me to post this :sweat_smile:  ![image](https://user-images.githubusercontent.com/1471350/164045405-4640b6a3-a6b9-4b69-9a50-c49556dd7602.png)

The [Wiki page](https://en.wikipedia.org/wiki/Aral_Sea) does indeed read:

> Formerly the fourth [largest lake](https://en.wikipedia.org/wiki/Largest_lake) in the world with an area of 68,000 km2 (26,300 sq mi), the Aral Sea began shrinking in the 1960s after the rivers that fed it were diverted by [Soviet](https://en.wikipedia.org/wiki/Soviet_Union) [irrigation](https://en.wikipedia.org/wiki/Irrigation) projects. By 1997, it had declined to 10% of its original size, splitting into four lakes: the [North Aral Sea](https://en.wikipedia.org/wiki/North_Aral_Sea), the eastern and western basins of the once far larger [South Aral Sea](https://en.wikipedia.org/wiki/South_Aral_Sea), and the smaller intermediate [Barsakelmes Lake](https://en.wikipedia.org/wiki/Barsakelmes_Lake).[[5]](https://en.wikipedia.org/wiki/Aral_Sea#cite_note-sciam-5)

Should it be split up into the North, East, and West? :thinking:

**Comment by aplaice** [comment]
> Should it be split up into the North, East, and West? thinking

Perhaps, though we don't actually have any criteria for inland lakes/seas, and the Aral Sea is there by inertia.

I guess that once we have proper criteria, neither the North/East/West Aral Sea, nor the Sea of Galilee nor the Dead Sea will be fit for inclusion. :) (Except in the very unlikely case where we use a cultural criterion (which is very subjective, so I don't think it'd be a good idea), in which case the original Aral Sea might actually scrape in, due to its symbolic importance...)

(I've not been pressing for figuring out criteria for inland seas/lakes, since:

1. We still haven't fully applied the updated criteria for ocean-connected seas.
2. I like the maps that I created for the Aral Sea, the Sea of Galilee and the Dead Sea (the map of the Aral Sea even more-or-less reflects reality). ;) (not that that's a real reason to keep them, once the time for swinging the axe comes!)

)

**Comment by axelboc** [comment]
Closing as the decision to keep/remove/move the Aral sea will be part of a broader discussion... eventually. 😅
