### ISSUE TITLE
Kazakhstan capital name is back to Astana

### ISSUE THREAD

**Issue by mbugert** [anki-geo/ultimate-geography#569]
The 2019 name change of the Kazakh capital (from Astana to Nur-Sultan) is being reverted.

Sources:
* https://www.theguardian.com/world/2022/sep/14/kazakhstan-to-change-name-of-capital-from-nur-sultan-back-to-astana
* https://www.sueddeutsche.de/politik/hauptstadt-kasachstans-hauptstadt-soll-wieder-astana-heissen-dpa.urn-newsml-dpa-com-20090101-220916-99-785163

**Comment by horwitz** [comment]
any chance the name change hasn't happened quite yet?
```
Presidential spokesman Ruslan Zheldibai said on September 13 that the move will be added to a bill of amendments to the constitution currently under preparation.
```
(from [here](https://www.rferl.org/a/kazakhstan-nur-sultan-vote-astana/32035136.html))

(and even if it hasn't happened just yet, this is (IMO) good to track!)

**Comment by axelboc** [comment]
The [Wikipedia page] (https://en.wikipedia.org/wiki/Astana?wprov=sfla1) has already been renamed 👀

**Comment by aplaice** [comment]
Great, quick catch — thanks!

I'd wait a couple of months in case Nazarbeyev's faction regains some power, and then make the change, to avoid back-and-forth.

<hr/>

Once we do, I think that this is a case where it'd be worth having the full date range for the previous capital name (something like: "Briefly renamed to Nur-Sultan (2019-2022)."?). (cf. #545.)

**Comment by KentGrigo** [comment]
I've made a PR for this issue here: https://github.com/anki-geo/ultimate-geography/pull/571
I didn't notice this issue until after so I wasn't aware of your suggestion, @aplaice.
I went with the solution with minimal change `Known as Nur-Sultan until September 2022.` instead of `Known as Astana until March 2019.`
That way I was hopefully able to fix it for all the languages, though I had to remove the name of the month.
