### ISSUE TITLE
How do I get pronunciation on the ultimate geography deck? 

### ISSUE THREAD

**Issue by Firdoost** [anki-geo/ultimate-geography#572]
I downloaded the ultimate geography deck from the Ankiweb and it's pretty cool, but it does not have any sort of pronunciation. I can't use Awesome TTS because it wants me to specify the language for the text that it is pronouncing. Is there anywhere I can go to get audio for the ultimate geography deck?

**Comment by aplaice** [comment]
Thanks for the suggestion!

This is a topic that we've been (excessively?) discussing for a while, with a few potential solutions, each with various problems, here: #81. Please feel free to comment there! Please also feel free to make a stab at an implementation, if you have time. (I personally would be happy with even a partially-flawed implementation as a variant deck.)

Technically, using Awesome TTS, with English as the language might work if whatever TTS backend you're using is sufficiently good. (I haven't tried any, so I can't tell if there are any such.) After all, you're interested in the pronunciation English, not in the native language(s) of the country. The key stumbling block is that if the TTS engine isn't good-enough, then it'll mangle the countries with unusual pronunciations, which are obviously the ones that you'd be most interested in. The worst case would be if it gives a plausible but wrong pronunciation, and I'm not sure how to work around that. :/

**Comment by Firdoost** [comment]
Thanks for the response! I am surprised that no one has cracked this problem, but It does seem to be quite a difficult problem to fix. I can only kind-of code in HTML and CSS, so I probably wouldn't be of much use for solving the problem. My hard core WH teacher is making my high school class learn all of the countries, and, luckily, he has provided a resource to get accurate pronunciations. I am just going to have to bite the bullet and manually find mispronounced country names then replace them with correct ones. Using Anki to get a 100% on every quiz and test is worth the trouble though.

**Comment by Firdoost** [comment]
I am not too sure how accurate the resource that my teacher suggested is though. Accurate pronunciation seems to be quite elusive according to the page that you suggested me to look at.

**Comment by ukanuk** [comment]
> It does seem to be quite a difficult problem

To be clear, Anki and Brainbrew make it incredibly easy to add pronunciations, whether IPA, audio, or something else.

The difficulty is in the social perspective.

Who decides what does/doesn't get included in this deck? For places with multiple pronunciations, which region's pronunciation is "correct"? One person wants audio files for the entire deck that always autoplay, but that is incredibly annoying to another person is frequently embarrassed in public because they forgot to turn down their phone volume.

To sidestep the issues personally, I changed my card style to links to the names to go directly to a Forvo pronunciations webpage. (I shared this code in #81, see [my comment](https://github.com/anki-geo/ultimate-geography/issues/81#issuecomment-571617274 )  for additional links and better styling if you're interested) 

```
<div class="value">
	<a class=unobtrusive href="https://www.wikipedia.org/wiki/Special:Search?search={{Capital}}">{{Capital}}</a>
	 &nbsp;
	<a class="unobtrusive" style="font-size: 90%; vertical-align: top; " href="https://forvo.com/word/{{Capital}}/#en">🔊&#xFE0E;</a>
</div>
```

**Comment by axelboc** [comment]
FYI, @Firdoost, if you decide to go with @ukanuk's clever solution, the README has a section on how to [preserve modifications to the deck's templates](https://github.com/anki-geo/ultimate-geography#changes-that-are-or-can-be-preserved-) when upgrading.
