### ISSUE TITLE
Yemen Flag vs Monaco Flag

### ISSUE THREAD

**Issue by fredrikcoulter** [anki-geo/ultimate-geography#593]
When I was going through the deck today, both the Yemeni flag and the Monaco flag appeared.  I figured out why I was having problems differentiating them.  On my Android version of Anki, the bottom black bar did not appear on the Yemeni flag, which made it extremely difficult to differentiate it from the Monaco flag which doesn't have a black bar.

I don't know if the flags should have a frame in a contrasting color (white?) or if there's something wrong specifically with the Yemeni flag.  But it would be nice if I could see the black bar on the bottom of the flag.  (Interestingly, I can see the black bar at the top of the German flag.)

**Comment by aplaice** [comment]
Thanks for reporting!

This is strange, there should be a [slight white border/"glow" around the flag and it should be symmetric](https://github.com/anki-geo/ultimate-geography/blob/master/src/note_models/style.css#L93). (On my Android device I can indeed see a border around the Yemeni flag.)

Maybe the border is not wide enough and when the brightness of the screen is too low, it stops being visible (so maybe we should make the border wider)? Does changing the CSS to, say:

```
.nightMode .value > img:not([src*="-nobox"]),
.night_mode .value > img:not([src*="-nobox"]) {
  box-shadow: 0 0 4px 4px rgba(54, 54, 54, 0.9);
}
```

(i.e. with a ["spread-radius"](https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow) of 4px instead of 1px) help with the Yemeni flag on your device?

(`Three dots > Manage note types > Ultimate Geography (long-press) > Edit cards > Styling` to change styling on Ankidroid itself. You can find the Yemeni flag again via the card browser.)

**Comment by fredrikcoulter** [comment]
Yeah, if I look really carefully I can see the border.  So I guess you can close this issue.

**Comment by aplaice** [comment]
> Yeah, if I look really carefully I can see the border.

Thanks for checking! I'm glad that it's not a it's-completely-absent bug! 

However, if it's only visible when one looks really carefully (on your device/with your brightness settings — which probably aren't that unusual), that's still suboptimal, so we might want to adjust the settings. I'll try to look into this again at some point™..
