### ISSUE TITLE
Remove Republic of Artsakh

### ISSUE THREAD

**Issue by rlanday** [anki-geo/ultimate-geography#611]
The Republic of Artsakh will cease to exist no later than January 1, 2024 (most of its population has fled already):
https://www.reuters.com/world/asia-pacific/nagorno-karabakh-republic-will-cease-exist-jan-1-2024-nagorno-karabakh-2023-09-28/

**Comment by aplaice** [comment]
Pretty unfortunate. :(

We shouldn't get ahead of the relevant Wikipedia article (which still doesn't consistently use the past tense) and the list of states, but yes, we'll almost certainly be removing it, quite soon.

**Comment by Visne** [comment]
I guess Azerbaijans map should also be updated (when this goes through), since they will be controlling the territory both de jure and de facto, I think.

**Comment by horwitz** [comment]
assuming that the Republic of Artsakh does cease to exist on January 1, 2024, is this the correct list of tasks that need to be done (on or after January 1) to resolve this issue?

- remove "Republic of Artsakh" note
- update map image on the "Azerbaijan" note

**Comment by aplaice** [comment]
> assuming that the Republic of Artsakh does cease to exist on January 1, 2024, is this the correct list of tasks that need to be done (on or after January 1) to resolve this issue?
>
>     remove "Republic of Artsakh" note
>     update map image on the "Azerbaijan" note

Yes, in terms of forward-facing changes to the deck. (We probably don't even need to wait for 2024, as the situation is pretty clear by now.) For the image we probably simply need to switch to using https://commons.wikimedia.org/wiki/File:Azerbaijan_in_its_region.svg (instead of the current image https://commons.wikimedia.org/wiki/File:Azerbaijan_in_its_region_(claimed_hatched).svg)

<hr/>

However, there's also the question of handling the note for our current users.  I believe that this is the first time we're in a situation where we're removing a note because it's becoming outdated.

(We've had many cases of updating notes with updated info — e.g. new capitals — or removing notes because we've changed our inclusion criteria (but the notes themselves are still correct).  In both of these cases, upon simply updating, the user will not have any wrong (outdated) info. We've, not, however, had a situation where we're removing a note that is now becoming outdated, such that upon simply updating the deck, the user will be left with a wrong note.)

I believe that the simplest/sufficient approach is to just **mention Artsakh and its removal in the release notes** (and mention that if a current user wants the note removed, they have to manually remove it themselves).

(Ideally, CrowdAnki would have a way of deleting notes (in a user-respectful way, such that they can opt out — ideally the deck maintainers should have a way of providing a reason for deletion ("no longer meets inclusion criteria" vs. "outdated info")), but it currently doesn't.)

An alternative approach would be to update the country info to say "Artsakh was... until ..." (and update the Azerbaijan map) for v5.2, and only remove the note in v5.3, such that users who update step-by-step (but are deletion-averse or in a hurry/don't read the release notes) are left with correct information, but it's probably overkill!

**Comment by axelboc** [comment]
Interesting case indeed. While the v5.2/v5.3 approach is clever, I think that mentioning the deletion (and process to remove the card) clearly at the top of the release notes is sufficient. We can maybe provide a script for removing the note quickly?

**Comment by aplaice** [comment]
> We can maybe provide a script for removing the note quickly?

We could, but I'm not sure if it's worth it for one note vs. open browser (<kbd>b</kbd>), search for "Republic of Artsakh", make sure that the note is in the Ultimate Geography deck (assuming the user hasn't moved their notes), right-click, click "Notes" and click "Delete" (or just directly click "Delete" for older versions of Anki). (Deleting notes is a relatively normal thing that people will likely be familiar with?)

**Comment by aplaice** [comment]
I've added a section to the upgrade instructions:

https://github.com/anki-geo/ultimate-geography/wiki/Upgrade-instructions#from-v51-to-v52-preliminary

(feel free to edit as necessary!)

I _think_ that this is the only possibly unexpected behaviour when upgrading from 5.1 to 5.2?
